server:
  port: 8082
# choice

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CH
    username: postgres
    password: 123456


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

